import { useEffect, useState } from 'react';
import { useAuth } from '../context/AuthContext';
import TrainerCard from '../components/TrainerCard';
export default function ClassesPage() {
  const { token } = useAuth(); const [trainers,setTrainers] = useState([]); const [loading,setLoading] = useState(true); const [error,setError] = useState(''); const [search,setSearch] = useState(''); const [message,setMessage] = useState('');
  const [form,setForm] = useState({ trainer:'', className:'', date:'', timeSlot:'' });
  useEffect(() => { fetch('/api/v1/trainers').then(response => response.ok ? response.json() : Promise.reject(new Error('Could not load trainers'))).then(data => setTrainers(data.trainers)).catch(err => setError(err.message)).finally(() => setLoading(false)); }, []);
  function change(event) { setForm({ ...form, [event.target.name]: event.target.value }); }
  async function book(event) { event.preventDefault(); const response = await fetch('/api/v1/bookings',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({trainerId:form.trainer,className:form.className,date:form.date,timeSlot:form.timeSlot})}); const data = await response.json(); setMessage(response.ok ? 'Booking confirmed.' : data.message); }
  const visible = trainers.filter(trainer => trainer.specialization.toLowerCase().includes(search.toLowerCase()));
  return <><section className="intro"><p className="eyebrow">TRAINING FLOOR</p><h1>Find your next class</h1><input placeholder="Search specialization" value={search} onChange={event => setSearch(event.target.value)} /></section>{loading && <p>Loading trainers...</p>}{error && <p className="error">{error}</p>}<section className="trainer-grid">{visible.map(trainer => <TrainerCard key={trainer._id} {...trainer} />)}</section><section className="panel"><h2>Book a class</h2><form className="booking-form" onSubmit={book}><select name="trainer" value={form.trainer} onChange={change} required><option value="">Choose trainer</option>{trainers.map(trainer => <option key={trainer._id} value={trainer._id}>{trainer.name}</option>)}</select><input name="className" placeholder="Class name" value={form.className} onChange={change} required /><input type="date" name="date" value={form.date} onChange={change} required /><select name="timeSlot" value={form.timeSlot} onChange={change} required><option value="">Time slot</option><option>07:00 AM</option><option>06:00 PM</option></select><button>Book now</button></form><p>Selected trainer: {form.trainer ? trainers.find(t => t._id === form.trainer)?.name : 'None'} | Slot: {form.timeSlot || 'None'}</p>{message && <p>{message}</p>}</section></>;
}